### ISSUE TITLE
uuid dependency

### ISSUE THREAD

**Issue by lodemo** [nbspou/dart-oauth1#2]
There is a uuid 2.0.0 release available, can you update the pubspec to allow the new release?

**Comment by kaetemi** [comment]
Any breaking changes?

**Comment by lodemo** [comment]
According to https://pub.dartlang.org/documentation/uuid/latest/, yes. 
Not sure in what extend as the changes are not compared directly.

After reviewing the uuid usage in this repo it seems for me its currently isnt used at all?
The import and usage in [authorization_header.dart](https://github.com/nbspou/dart-oauth1/blob/fork/nbspou/lib/src/authorization_header.dart) is commented out.

**Comment by elMuso** [comment]
YES , it can be deleted from the pubspec.yaml file. This plugin is incompatible with https://github.com/pichillilorenzo/flutter_inappbrowser because of this dependency . Wich makes the whole point of having oauth1 without any browser to open the link with
