### ISSUE TITLE
oauth_callback_confirmed for wrongly implemented backends

### ISSUE THREAD

**Issue by ThexXTURBOXx** [nbspou/dart-oauth1#6]
I have tried using this library in my flutter application, but I have found, that the API I am trying to access, has a faulty OAuth implementation.
When requesting the temporary credentials, it returns `oauth_callback_confirmed=1` instead of `oauth_callback_confirmed=true`.
As I have seen across the internet, many APIs are implemented in this way (which is not the RFC 5849 norm, I know).
Therefore, many users could have this problem right now (or in the future).
The issue in [this line](https://github.com/nbspou/dart-oauth1/blob/fork/nbspou/lib/src/authorization.dart#L56).
One could add another case to it, where it checks like this;
```
String confirmed = params['oauth_callback_confirmed'].toLowerCase();
if (confirmed != 'true' || confirmed != '1') {
```
But I don't know, if it is the right way to include support for faulty implementations in libraries like this one.

Is there maybe any way I could solve the issue myself here or does it really need changes in the library?

**Comment by kaetemi** [comment]
Yes, supporting faulty implementations is fine. Make a pull request here to modify it, I'll push it onto the Dart pub thing.

RFC 1122, "Be liberal in what you accept, and conservative in what you send", https://tools.ietf.org/html/rfc1122#page-12.

**Comment by ThexXTURBOXx** [comment]
Okay, thank you very much. I created a PR, which should fix this behavior.
